### ISSUE TITLE
topology or homotopy theory?

### ISSUE THREAD

**Issue by marcbezem** [marcbezem/ZTors#2]
{\em Synthetic homotopy theory} is the study of the homotopy theoretic properties of types.  It is a fruitful one, because it turns out that
many of the most basic results of standard homotopy theory have true analogues for types, even though the framework, based purely on logical
principles, is devoid of the features one normally associates with topology, such as the topology of the real numbers.

@DanGrayson did you perhaps mean to write "homotopy theory" instead of the last but one "topology"?

**Comment by DanGrayson** [comment]
No.  A natural expectation is that a subject called something like "homotopy theory" would be based on something called "topology", since the way the classical subjects are related.  Somewhat surprising initially is that a sensible notion of "path" arises without first having a notion of "continuous map" or "unit interval".

**Comment by marcbezem** [comment]
Such as in, e.g., simplicial sets?

**Comment by DanGrayson** [comment]
Well, yes, with simplicial sets one gets a treatment of homotopy theory that is combinatorial and divorced from topology, too, but it doesn't have the flavor of synthetic homotopy theory, the formalism is much more intricate.

**Comment by mikeshulman** [comment]
A possible compromise phrase between "topology" and "homotopy theory" would be "algebraic topology".

**Comment by DanGrayson** [comment]
I guess, but I had something concrete in mind: the set of continuous maps from [0,1] to X, which has not algebraic flavor to it, although that is tacked on later.

**Comment by mikeshulman** [comment]
I do think @marcbezem has a point that simplicial homotopy theory is also devoid of the features one normally associates with topology.  I agree that this has a different flavor than synthetic homotopy theory, but the paragraph as written doesn't say anything to distinguish them.

**Comment by DanGrayson** [comment]
Okay, does this sound better?:

{\em Synthetic homotopy theory} is the study of the homotopy theoretic properties of types. It is a fruitful one, because it turns out that many of the most basic results of standard homotopy theory have true analogues for types, even though the framework, based purely on logical principles, is devoid of the features one normally associates with homotopy theory, such as an implementation involving topological spaces and continuous maps between them, or an implementation involving simplicial sets and fibrant replacement.

**Comment by mikeshulman** [comment]
That's good, but it's a pretty long sentence.  How about

{\em Synthetic homotopy theory} is the study of the homotopy theoretic properties of types. It is a fruitful one, because it turns out that many of the most basic results of standard homotopy theory have true analogues for types.  This is true even though the framework is based purely on logical principles, rather than implemented like traditional homotopy theory in terms of topological spaces and continuous maps or combinatorial structures such as simplicial sets and fibrant replacement.

**Comment by DanGrayson** [comment]
Sounds good to me.
